export default {
  about_chat: '一起来讨论',
  about_download_sdk: '下载SDK',
  about_email: '加入邮件组',
  about_know: '一起来了解',
  about_use: '一起来使用',
  about_yellow_paper: '星云指数黄皮书',
  ad_current_nr_title: '今日星云指数',
  ad_eth_address_title: '以太坊地址:',
  ad_last_nr_date: '最近一次链上行为发生在 {0}',
  ad_last_nr_title: '历史回顾',
  ad_last_nr_value: '当天星云指数为 {0}',
  ad_last_seven_day_nr_title: '近7天星云指数变化',
  ad_neb_address_title: '星云主网地址: ',
  ad_net_error: '当前网络异常，请稍后重试',
  ad_no_result: '抱歉! 没有找到相关搜索结果',
  ad_nr_update_time: '北京时间每天9点更新星云指数',
  ad_nr_value: '星云指数',
  ad_search_placeholder: '输入星云主网地址，查询星云指数',
  ad_title: '星云指数查询结果详情',
  ad_value_desc: '核心星云指数结合转账记录、账户余额等多种因素，反映该地址对整个经济体的贡献度。',
  ad_zero_desc: '该地址最近没有发生转账等链上行为。',
  err_addr_empty: '请输入星云主网地址',
  err_addr_length: '地址位数35位哦！',
  err_addr_n1: '星云主网地址以n1开头',
  err_addr_not_neb: '这不是星云主网地址',
  err_go_home: '回到首页重新搜索',
  header_download_sdk: '下载SDK',
  header_official_website: '星云官网',
  mr_desc: '注：图中数据更新至2018年11月15日',
  nova_dip_desc: '给予区块链应用开发者链上原生激励',
  nova_dip_sub_title: 'Developer Incentive Protocol (DIP)',
  nova_dip_title: '开发者激励协议',
  nova_download: '下载星云指数SDK',
  nova_nbre_desc: '使区块链核心协议可即时升级',
  nova_nbre_sub_title: 'Nebulas Blockchain Runtime Environment (NBRE)',
  nova_nbre_title: '星云区块链可执行环境',
  nova_nr_desc: '衡量区块链世界链上数据价值',
  nova_nr_sub_title: 'Nebulas Rank (NR)',
  nova_nr_title: '星云指数',
  nova_title: '什么是Nebulas NOVA',
  ranking_title: '星云指数（Nebulas Rank,NR）',
  ranking_title1: '核心星云指数反映经济体贡献度，反映市值变化',
  search_btn_random: '试试随机地址',
  search_placeholder: '输入星云主网地址，查询星云指数',
  search_support_eth: '即将支持以太坊地址星云指数查询，敬请期待',
  search_title: '发现区块链数据的价值',
  use_case_atp_content: '星云指数是链上衡量节点贡献值的标尺。星途协议（ATP）基于星云指数构建核心算法，定义区块链互动广告营销新范式。',
  use_case_atp_keys: '营销/广告/智能空投',
  use_case_atp_title: '星途协议',
  use_case_dip_content: '星云将给予区块链应用开发者链上原生激励。开发者激励协议构建一个反馈循环，激励开发者研发高质量的去中心化应用。',
  use_case_dip_keys: '开发者激励',
  use_case_dip_title: '星云链',
  use_case_more: '了解更多',
  use_case_sc_content: '星云指数可以通过多重维度展现账户的链上活动。Searchain作为链上交易数据统计网站，接入星云指数，将有助于其丰富链上数据维度。',
  use_case_sc_keys: '统计/分析',
  use_case_title: '合作伙伴 & 应用场景',
  use_case_tm_content: '星云指数可以衡量账户地址对于区块链的贡献度，同时一段时间内的以太坊核心NR的走势也展现出了同以太坊市值的强相关性。TokenMania将把星云指数作为数字资产交易的重要参考指标。',
  use_case_tm_keys: '数字资产管理'
}
