export default {
  about_chat: 'Let\'s chat',
  about_download_sdk: 'Download SDK',
  about_email: 'Join our E-mail group',
  about_know: 'Start to learn',
  about_use: 'Start to use',
  about_yellow_paper: 'Nebulas Rank Yellowpaper',
  ad_current_nr_title: 'Today\'s NR value',
  ad_eth_address_title: 'Ethereum address:',
  ad_last_nr_date: 'Latest on-chain behaviors happended on {0}',
  ad_last_nr_title: 'History',
  ad_last_nr_value: 'NR value on the day is {0}',
  ad_last_seven_day_nr_title: 'NR value of past 7 days',
  ad_neb_address_title: 'Nebulas mainnet address:',
  ad_net_error: 'The network is currently unavailable. Please try again later.',
  ad_no_result: 'Sorry... No search results found',
  ad_nr_update_time: 'Update latest NR data at 9:00 (UTC+8) everyday.',
  ad_nr_value: 'NR Value',
  ad_search_placeholder: 'Enter a Nebulas mainnet address',
  ad_title: 'NR search results',
  ad_value_desc: 'Core Nebulas Rank reflects the economy contribution of the address according to transaction record, account balance and other factors.',
  ad_zero_desc: 'The address has no transaction or other on-chain behaviors recently.',
  err_addr_empty: 'Please enter a Nebulas mainnet address.',
  err_addr_length: '35 characters.',
  err_addr_n1: 'The Nebulas mainnet address begins with n1.',
  err_addr_not_neb: 'This is not Nebulas mainnet address.',
  err_go_home: 'Back to home page and search again',
  header_download_sdk: 'Download SDK',
  header_official_website: 'Nebulas.io',
  mr_desc: 'Note: data in the pics updated to Nov 15, 2018  ',
  nova_dip_desc: 'To provide the native on-chain incentive for developers',
  nova_dip_sub_title: 'Developer Incentive Protocol',
  nova_dip_title: 'DIP',
  nova_download: 'Download NR SDK',
  nova_nbre_desc: 'To upgrade the core protocols immediately',
  nova_nbre_sub_title: 'Nebulas Blockchain Runtime Environment',
  nova_nbre_title: 'NBRE',
  nova_nr_desc: 'To measure the value of on-chain data',
  nova_nr_sub_title: 'Nebulas Rank',
  nova_nr_title: 'NR',
  nova_title: 'What is Nebulas NOVA',
  ranking_title: 'Nebulas Rank',
  ranking_title1: 'Core Nebulas Rank reflects the economy contribution and market cap change.',
  search_btn_random: 'Try random address',
  search_placeholder: 'Enter a Nebulas mainnet address to see the NR value',
  search_support_eth: 'Soon to support Ethereum NR inquiry, stay tuned!',
  search_title: 'Discover the Value of Blockchain Data',
  use_case_atp_content: 'Nebulas Rank is the standard to measure value and contribution accounts have on a blockchain. Atlas Protocol is based on the Nebulas Rank core algorithm, defining blockchain interactive advertising and marketing. ',
  use_case_atp_keys: 'Marketing/Advertising/Smartdrop',
  use_case_atp_title: 'Atlas Protocol',
  use_case_dip_content: 'Nebulas provides the native on-chain incentive for developers. DIP provides a feedback loop for developers to create high-quality distributed applications.',
  use_case_dip_keys: 'Developer Incentive',
  use_case_dip_title: 'Nebulas',
  use_case_more: 'Learn More',
  use_case_sc_content: 'Nebulas Rank shows the on-chain activity of account through multi-dimension perspectives. Searchchain, an on-chain transaction data statistic website, access into Nebulas Rank, which will help increase the on-chain data dimensions.',
  use_case_sc_keys: 'Stats/Analytics',
  use_case_title: 'Scenario for application & partnership',
  use_case_tm_content: 'Nebulas Rank measures the contribution of address to blockchain. Meanwhile, NR value of Ethereum has strong correlation to Ethereum market value. TokenMania will utilize Nebulas Rank as a significant refernce for Digital asset trading.',
  use_case_tm_keys: 'Digital Assets Management'
}
